name: CI - Multi Project Pipeline

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
#dsasdsad
permissions:
  actions: read
  contents: read
  security-events: write
  issues: write
##sadcawasas
jobs:
  run-pipeline:
    uses: PruebaActions/WorkFlows-Templates/.github/workflows/pr-dotnet-codeql-final.yaml@main
    with:
      codeql_language: "csharp"
      has_tests: false
      project_paths: |
        [
          { "path": "./Website.sln", "isFramework": "false" }
        ]

      docker_targets: |
        [
          {
            "image_name": "website-pr",
            "container_name": "website-pr-container",
            "dockerfile": "./Website/Dockerfile",
            "container_port": "80",
            "isFramework": "false"
          }
        ]
